### PR TITLE
reload button mockup and visual cues on saving

### PR DESCRIPTION
**Pull request by jprado1**
Implementation of a reload button for answer (to recover saved version of an answer after bad changes) and visual cues for saving functionality.
Points to discuss:
- Visual cues on saving : css options for the saving button and the implementation. As a default, the visual cue is the 'success' style from ipywidgets. In terms of implementation, I tried to mimic ```CodeDemoStatus```for the much smaller saving button, let me know if its overkill or not clear enough. 
- Reload button : when I implemented the button, I realised that it is a potential risk for students if they reload an (empty) answer before saving. The reload button does not interact with the json file, so the effect has small range, but still important to discuss. I feel that if the button is validated and stays in the library, it should be moved as far away as possible from the save button, in order to avoid miss clicks. Other points to discuss are the button text, implementation (normally encapsulated in ```Answer``` and ```AnswerRegistry```)

An example : 

https://user-images.githubusercontent.com/98404937/205985206-fbee3cbe-c08a-4017-b091-bc65b3b549d2.mp4

### CODE REVIEW

**Comment by agoscinski** [comment]
Thanks for the implementation. Also thanks for the video, it is very useful to get a quick impression. I like the green effect, seems to me very clear.


>  I see a potential risk of miss clicks for students, but one could imagine that the 'Reload button' would be a feature that the teacher could toggle when initialising each Answer class

I share the same doubts. Maybe we add a global TEACHER_MODE flag that needs to be set **before** the initialization of the widget so that the reload button appears. That way the code stays simple, since we don't need to observe the TEACHER_MODE variable and act on changes like in the `teacher_mode_vertical_slice` branch.

**Comment by ceriottm** [comment]
I also like a lot the green effect. Perhaps one could do something similar also with the check button. 
As for the "reload" I was thinking this could actually be very useful for the students, if they want to play around with an answer and then revert to saved. If you think that the risk of loading an empty value is more than the advantage, then I would just have a "reload" button for the answerregistry widget, so one has to scroll all the way up to click. I would also add a "save all" button there that triggers saving all registered answers

**Comment by jprado1** [comment]
New features:
- A save all button next to the place where students load their AnswerRegistry (require button press to confirm save all)
- Reload saved answer now requires button press to confirm
- Visual cues are now implemented also on button color.

Points to discuss : 
- For the moment, the implementation of the confirmation request is separate for reloading a given answer and for saving all answers in the registry. I think the best would be to define it only once. Before doing this, I'd just like to confirm where this should go ? (in utils.py or in answer.py)
- The color code is inverted between saving and checking updating : check and update buttons are colourful when check and update is needed, and save button is collourful after a success save. I kept like this to be consistent with the visual cue at the left side of the code demo/parboxes, but I think that a decision should be made so either:
1. all buttons are colourful when they need to be pressed
2.  all buttons are colourful when they were pressed and behaved correctly 

https://user-images.githubusercontent.com/98404937/206439074-40b6e05c-0bbe-4639-b64f-b6a4ce6dc232.mp4

**Comment by agoscinski** [comment]
> For the moment, the implementation of the confirmation request is separate for reloading a given answer and for saving all answers in the registry. I think the best would be to define it only once. Before doing this, I'd just like to confirm where this should go ? (in utils.py or in answer.py)

no preference, it would probably put them in a separate file _state_widgets.py as in the `teacher_mode_vertical_slice` branch

> The color code is inverted between saving and checking updating : check and update buttons are colourful when check and update is needed, and save button is collourful after a success save. I kept like this to be consistent with the visual cue at the left side of the code demo/parboxes, but I think that a decision should be made so either:

I think 1. makes more sense. You want to reminded by the color that things have changed, while if things haven't changed the button needs no attention of the users

**Comment by ceriottm** [comment]
On Thu, 8 Dec 2022 at 14:54, agoscinski ***@***.***> wrote:

> For the moment, the implementation of the confirmation request is separate
> for reloading a given answer and for saving all answers in the registry. I
> think the best would be to define it only once. Before doing this, I'd just
> like to confirm where this should go ? (in utils.py or in answer.py)
>
> no preference, it would probably put them in a separate file
> _state_widgets.py as in the teacher_mode_vertical_slice branch
>

no preference either


> The color code is inverted between saving and checking updating : check
> and update buttons are colourful when check and update is needed, and save
> button is collourful after a success save. I kept like this to be
> consistent with the visual cue at the left side of the code demo/parboxes,
> but I think that a decision should be made so either:
>
> I think 1. makes more sense. You want to reminded by the color that things
> have changed, while if things haven't changed the button needs no attention
> of the users
>
I agree. Color indicates that the button needs attention. Perhaps you can
use a shade of purple, anyway make it subtle and not too much in your face
IMO

**Comment by jprado1** [comment]
I am sorry for the strange behaviour on the save all button, I was also working on a better implementation of the confirmation button and just pushed, normally keeping your last push intact.

**Pull request merged**
